### ISSUE TITLE
[QST] Transform Reduce - Kernel Fusion possible?

### ISSUE THREAD

**Issue by pauleonix** [NVIDIA/MatX#139]
Use the form below to ask a question about MatX. This can be anything from a code question to questions about releases.
Hi, on first sight of this project I had hoped that the deferred executors would allow for fusing transformations into reductions. But after trying it out I'm not so sure anymore:
```c++
int const row = 3;
int const col = 4;
auto tensor = matx::make_tensor<int, 2>({row, col});
tensor.SetVals({{3, 2, 4, 5},
                {0, -2, 3, 1},
                {9, 8, 7, 6}});
tensor.Print(0,0);
auto count = matx::make_tensor<int, 1>({row});

// Goal: For each row, count the number of elements greater than 2.
matx::sum(count, tensor > 2);
cudaDeviceSynchronize();
count.Print(0);
```
This code compiles and runs, but the result is not the expected `{3, 1, 4}`, but {1, 1, 1}. 
Running the transformation and reduction independently works as expected:
```c++
(tensor = tensor > 2).run();
matx::sum(count, tensor);
```
Is or will it be possible to avoid unnecessary reads/writes to `tensor` by kernel fusion in MatX?

**Comment by cliffburdick** [comment]
Hi Paul, what you're looking for is the select/find reduction , followed by a sum. it cannot be done in a single step currently, but two separate reductions will work. here is how to use find() with a greater than operator:

https://github.com/NVIDIA/MatX/blob/104fc4fe12d405778d01835d5f87a5070422e097/test/00_operators/ReductionTests.cu#L520

after you do this you would call sum() on the resultant tensor. 

we may be able to fuse this into a single kernel, but see if the performance of this is fast enough and let us know. thanks.

**Comment by luitjens** [comment]
Cliff are you sure select/find are necessary?

It looks like he is just trying to count the number of elements > 2.  I
thought this was supported.

**Comment by pauleonix** [comment]
Thanks for the input! `matx::find` isn't documented yet, right? As I am rather looking for long term best practices than short term performance gains, `IFELSE` seems to be the way to go. The only problem is that 
```c++
matx::sum(count, matx::IFELSE(tensor > 2, 1, 0));
```
doesn't compile for me:
```
/home/pauleonix/MatX/include/matx_reduce.h(628): error: incomplete type is not allowed                                                                                                            
          detected during:
            instantiation of "void matx::detail::matxReduceKernel(TensorType, InType, ReduceOp, matx::index_t) [with TensorType=matx::tensor_t<int, 1, matx::basic_storage<matx::raw_pointer_buffer<int, matx::owning, matx::matx_allocator<int>>>, matx::tensor_desc_t<std::array<matx::index_t, 1UL>, std::array<matx::index_t, 1UL>, 1>>, InType=matx::IFELSE<matx::detail::matxBinaryOp<matx::tensor_t<int, 2, matx::basic_storage<matx::raw_pointer_buffer<int, matx::owning, matx::matx_allocator<int>>>, matx::tensor_desc_t<std::array<long long, 2UL>, std::array<long long, 2UL>, 2>>, int, matx::detail::BinOp<int, int, matx::detail::GTF<int, int>>>, int, int>, ReduceOp=matx::detail::reduceOpSum<int>]"                
(950): here                                                                                                                                                                                                          
            instantiation of "void matx::reduce(TensorType, TensorIndexType, InType, ReduceOp, cudaStream_t, __nv_bool) [with TensorType=matx::tensor_t<int, 1, matx::basic_storage<matx::raw_pointer_buffer<int, matx::owning, matx::matx_allocator<int>>>, matx::tensor_desc_t<std::array<matx::index_t, 1UL>, std::array<matx::index_t, 1UL>, 1>>, TensorIndexType=std::nullopt_t, InType=matx::IFELSE<matx::detail::matxBinaryOp<matx::tensor_t<int, 2, matx::basic_storage<matx::raw_pointer_buffer<int, matx::owning, matx::matx_allocator<int>>>, matx::tensor_desc_t<std::array<long long, 2UL>, std::array<long long, 2UL>, 2>>, int, matx::detail::BinOp<int, int, matx::detail::GTF<int, int>>>, int, int>, ReduceOp=matx::detail::reduceOpSum<int>, <unnamed>=true]"                                                                                                    
(1009): here                                                                                                                                                                                                         
            instantiation of "void matx::reduce(TensorType &, const InType &, ReduceOp, cudaStream_t, __nv_bool) [with TensorType=matx::tensor_t<int, 1, matx::basic_storage<matx::raw_pointer_buffer<int, matx::owning, matx::matx_allocator<int>>>, matx::tensor_desc_t<std::array<matx::index_t, 1UL>, std::array<matx::index_t, 1UL>, 1>>, InType=matx::IFELSE<matx::detail::matxBinaryOp<matx::tensor_t<int, 2, matx::basic_storage<matx::raw_pointer_buffer<int, matx::owning, matx::matx_allocator<int>>>, matx::tensor_desc_t<std::array<long long, 2UL>, std::array<long long, 2UL>, 2>>, int, matx::detail::BinOp<int, int, matx::detail::GTF<int, int>>>, int, int>, ReduceOp=matx::detail::reduceOpSum<int>]"               
(1158): here                                                                                                                                                                                                         
            instantiation of "void matx::sum(TensorType &, const InType &, cudaStream_t) [with TensorType=matx::tensor_t<int, 1, matx::basic_storage<matx::raw_pointer_buffer<int, matx::owning, matx::matx_allocator<int>>>, matx::tensor_desc_t<std::array<matx::index_t, 1UL>, std::array<matx::index_t, 1UL>, 1>>, InType=matx::IFELSE<matx::detail::matxBinaryOp<matx::tensor_t<int, 2, matx::basic_storage<matx::raw_pointer_buffer<int, matx::owning, matx::matx_allocator<int>>>, matx::tensor_desc_t<std::array<long long, 2UL>, std::array<long long, 2UL>, 2>>, int, matx::detail::BinOp<int, int, matx::detail::GTF<int, int>>>, int, int>]"       
/home/pauleonix/matx_count_by_row/count_by_row.cu(22): here
[...]
```
Should I open a new issue for this?

**Comment by cliffburdick** [comment]
hi @pauleonix I'll try it out this morning and see if it works and get back to you. if there's a bug we can open an issue.

**Comment by cliffburdick** [comment]
@pauleonix apologies, but what @luitjens said was correct, and this _should_ have worked already. We had a bug where the input type was used as an accumulator. Since `t>2` turns into a boolean value, it was accumulating booleans and the result would only be 1 or 0 when written into the output. If you grab the latest code, this is fixed.

Just for posterity, here are your options:
1) `matx::sum(count, tensor > 2);`. This will cause each thread to evaluate their element of `tensor > 2`, then perform a custom reduction.
2) `find(t1o, num_found, tensor, GT{2});`. This will trigger a `select` reduction using CUB, and return the sum in the `num_found` variable. It also gives you the actual values into the output tensor if you care about them. It may be faster than the first method for large tensor because it uses CUB, but I haven't proven that.

I'm closing this, but let us know if you still have issues.

**Comment by pauleonix** [comment]
Thanks for the fix! 
1. While I expect the resulting binary after optimization to be the same, I am still curious: Can you reproduce my problem with `IFELSE()` or know why it doesn't work that way?
2. While `find` is generally interesting it doesn't seem to be a good solution for the example given above, as 
> Num found output tensor rank must be 0

So it seems as if one can't simply use it for this kind of segmented reduction. I can only imagine a loop over calls to `find` on single-row-slices into the original tensor, ideally on different streams. Or am I overlooking something?

**Comment by cliffburdick** [comment]
Hi @pauleonix, that's correct right now for #2. CUB has a limitation of only selections down to 0D (ie no segmented select), so we currently support that. We might be able to do so in the future with a custom select implementation, but that's not there right now. You would have to do a loop as you pointed out.

For #1 I forgot that IFELSE is it does not have a type since it's designed to be executed by itself. We could change this, but it's a little ambiguous because you're allowed to mix different types. For example:

```
IFELSE(A > 0, B = 1, C = 2.0f)
```
In this case B could be an int, and C could be a float. The actual type of the operator is not clear at that point, and the reduction needs to know the type going in. Is this something you need or were you just curious?

**Comment by pauleonix** [comment]
I don't need it although I liked it due to it being more clear about what happens instead of implicitly converting `bool` to `int`. That being said, it is subjective/debatable which form is more readable, and I understand the problem with changing it. 
Thanks again for your time!

**Comment by cliffburdick** [comment]
@pauleonix we just added casting operators after discussing the problem you hit, so you can also use those to make it more clear. Something like: 
```
matx::sum(count, as_int(tensor > 2));
matx::sum(count, as_type<int>(tensor > 2));
```
These do the same thing, and make it clear that the bool is being casted. It's not needed anymore in the situation you first posted, but it may help readability.

**Comment by pauleonix** [comment]
Very cool! 
FYI: I used MatX in a SO answer: [Is there a function to perform nested thrust function?](https://stackoverflow.com/questions/71263160/is-there-a-function-to-perform-nested-thrust-function)
