### ISSUE TITLE
[FEA] We don't have unary operator `-`?

### ISSUE THREAD

**Issue by ZJUGuoShuai** [NVIDIA/MatX#148]
It seems like MatX don't have unary operator `-` currently, something like:
```cpp
// a, b are tensors
(b = -a).run();
```

I looked up the  the code, it turned out that the operator is commented:

<img width="487" alt="图片" src="https://user-images.githubusercontent.com/22856433/158723088-d35a6337-e68a-42d9-8236-25d3e14cf72c.png">

Why don't we add this operator?

**Comment by cliffburdick** [comment]
hi @ZJUGuoShuai, I will test it out to see why, but I seem to recall it caused an ambiguity in part of the code.

**Comment by cliffburdick** [comment]
Hi @ZJUGuoShuai this has been fixed, but github is having PR issues right now https://twitter.com/githubstatus/status/1504461742843346945

I'll merge once that's resolved.
