### ISSUE TITLE
[BUG] Problems with matx::reduce in the newest version

### ISSUE THREAD

**Issue by bonevbs** [NVIDIA/MatX#159]
There seems to be a bug in the newest version of MatX. `matx::reduce(x_norm, norm(x), detail::reduceOpSum<SType>(), stream, true);` does not seem to work anymore and always leads to 0 in the accumulation. Replacing the above line with `matx::sum(x_norm, norm(x), stream);` seems to have resolved the issue for me. I am not sure why that is, matx::sum seems to be derived from the general reduce operation?

**Comment by bonevbs** [comment]
Upon second inspection, this seems to be related to CUB reductions vs MatX reductions?

**Comment by cliffburdick** [comment]
thanks @bonevbs, I'll take a look. it's not related to cub vs non cub, but likely just an incompatibility with the old path.

**Comment by cliffburdick** [comment]
This is fixed in the latest commit
