### ISSUE TITLE
[BUG] Invalid cuQuantum SDK download link in cmake/FindcuTensorNet.cmake

### ISSUE THREAD

**Issue by ZJUGuoShuai** [NVIDIA/MatX#165]
**Describe the bug**
The cuQuantum SDK download link in [`cmake/FindcuTensorNet.cmake`](https://github.com/NVIDIA/MatX/blob/66bd5769973a113778c1a89fd88833af2166bfb0/cmake/FindcuTensorNet.cmake) is invalid (returns a 404 not found).

**To Reproduce**
The download link from that file is: 
```
https://developer.download.nvidia.cn/compute/cuquantum/redist/linux-x86_64/cuquantum-linux-x86_64-0.1.0.30-archive.tar.xz
```
And this gives me a **404 - Not Found**.

**Expected behavior**
The download link should be valid.

**Comment by ZJUGuoShuai** [comment]
Actually I manually installed the latest cuTensorNet (cuQuantum SDK) from https://developer.nvidia.com/cuquantum-downloads, but this installation (to `/opt/nvidia/cuquantum`) do not contain any CMake config files:

![image](https://user-images.githubusercontent.com/22856433/164608561-10e9e7f1-e19e-47b7-8bc3-4b9d5aab5488.png)

I ran cmake with
```
cmake .. -DMATX_EN_CUTENSOR=ON -Dcutensornet_DIR=/opt/nvidia/cuquantum
```
but it still cannot find cuTensorNet
```
...
-- Could NOT find cuTensorNet (missing: cuTensorNet_LIBRARY cuTensorNet_INCLUDE_DIR)
...
```
```

**Comment by ZJUGuoShuai** [comment]
The valid link is: https://developer.download.nvidia.com/compute/cuquantum/redist/cuquantum/linux-x86_64/cuquantum-linux-x86_64-0.1.0.30-archive.tar.xz

**Comment by cliffburdick** [comment]
thanks @ZJUGuoShuai, we'll get this fixed today.

**Comment by cliffburdick** [comment]
Hi @ZJUGuoShuai, we updated both cuTENSOR and cuTensorNet, and the issue has been fixed. The updated should also improve performance quite a bit.
