### ISSUE TITLE
[BUG] An empty macro MATX_ASSERT_STR_EXP is missing in matx_error.h when NDEBUG is defined

### ISSUE THREAD

**Issue by ZJUGuoShuai** [NVIDIA/MatX#177]
**Describe the bug**
An empty macro `MATX_ASSERT_STR_EXP` is missing in `matx_error.h` when `NDEBUG` is defined.

![image](https://user-images.githubusercontent.com/22856433/166646630-9714840b-8069-47d6-b4ce-1c38495b9eb6.png)

When building with `-DNDEBUG` (e.g. cmake with `-DCMAKE_BUILD_TYPE=Release`), this error will be thrown by the compiler:

```
/usr/local/include/matx_einsum.h(105): error: identifier "MATX_ASSERT_STR_EXP" is undefined
```

**Expected behavior**
An empty definition of `MATX_ASSERT_STR_EXP` should be added between `#else` and `#endif`, just like `MATX_ASSERT` and `MATX_ASSERT_STR`.

**System details (please complete the following information):**
 - OS: Ubuntu 20.04
 - CUDA version: CUDA 11.4
 - g++ version: 9.3.0

**Comment by cliffburdick** [comment]
Thanks for catching this @ZJUGuoShuai . This has been fixed.

**Comment by ZJUGuoShuai** [comment]
@cliffburdick I suddenly realized that it's not OK to use `MATX_ASSERT_*` to wrap `cutensornet*` APIs in [matx_einsum.h](https://github.com/NVIDIA/MatX/blob/main/include/matx_einsum.h) because if I build it in release mode (with `-DNDEBUG`), these APIs will be replaced by emtpy lines.

Actually I tried to compiled a `einsum()` program with `-DNDEBUG` and ran it, it really did no computation.

**Comment by cliffburdick** [comment]
Thanks @ZJUGuoShuai. fixing it now

**Comment by cliffburdick** [comment]
Hi @ZJUGuoShuai , it should be fixed. I verified the einsum tests pass in both debug and release mode.
