### ISSUE TITLE
[FEA] Add cub block radix sort when sort dimension is small

### ISSUE THREAD

**Issue by luitjens** [NVIDIA/MatX#224]
we should write a simple kernel that dispatches 1 sort batch per CTA using cub when the sorting dimension is small.  This would increase throughput and lower latency for batched sorting on small dims.

**Comment by luitjens** [comment]
Switching to DeviceSegmentedSort from DeviceSegmentedRadix solve this.

**Comment by tylera-nvidia** [comment]
Addressed in PR #272
