### ISSUE TITLE
[BUG] `einsum` is using too much extra GPU memory

### ISSUE THREAD

**Issue by ZJUGuoShuai** [NVIDIA/MatX#240]
**Describe the bug**
`matx::cutensor::einsum` is using too much extra GPU memory. Is this a bug or not?

**To Reproduce**
1. Make 3 tensors `t1`, `t2` and `out`:
```cpp
auto t1 = matx::make_tensor<float, 2>({32, 10});
auto t2 = matx::make_tensor<float, 2>({32, 10});
auto out = matx::make_tensor<float, 1>({32});
```
2. Using gdb to stop here, I can use `nvidia-smi` to check memory usage:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/22856433/183803221-46de28c0-c039-4531-9afe-c7dbc391c07b.png">

3. Perform operation `einsum` on `t1` and `t2` to calculate `out`:
```cpp
matx::cutensor::einsum(out, "ij,ij->i", 0, t1, t2);
```

4. After that single call, check the memory:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/22856433/183803809-c9c8264c-33dd-4cf5-803c-75a64a4a4e7e.png">

**It just took >2GB memory**, is this normal?

**Expected behavior**
`matx::cutensor::einsum` may use less or no extra memory. BTW, if it does need extra memory, when are these memory `free`d?

**Code snippers**
```cpp
#include <matx.h>
#include <matx_einsum.h>

int main() {
    auto t1 = matx::make_tensor<float, 2>({32, 10});
    auto t2 = matx::make_tensor<float, 2>({32, 10});
    auto out = matx::make_tensor<float, 1>({32});

    matx::cutensor::einsum(out, "ij,ij->i", 0, t1, t2);

    cudaDeviceSynchronize();

    return 0;
}
```

**System details (please complete the following information):**
 - OS: Ubuntu 20.04
 - CUDA version: CUDA 11.4
 - g++ version: 9.3.0

**Additional context**
Tested on latest commit 128e05ac7258ee4362aa164ac07bfbaa157fc117.

**Comment by leofang** [comment]
Thanks for reporting. Could you kindly rerun your executable with `CUTENSORNET_LOG_LEVEL=6 ./my_executable` and send us the log?

**Comment by luitjens** [comment]
Einsum uses cutensornet which does not say how much memory it needs. Instead you pass it a workspace.  We pass it 2G.  

https://github.com/NVIDIA/MatX/blob/128e05ac7258ee4362aa164ac07bfbaa157fc117/include/matx_einsum.h#L150

**Comment by leofang** [comment]
The 2GB is just a guidance for the path optimizer, it is not necessary that cutn would use all 2GB

**Comment by cliffburdick** [comment]
Hi @ZJUGuoShuai, this is old code we have left over from when cutensornet required the user to allocate a large chunk of memory instead of asking it how much. The newer version doesn't require this 2GB allocation, and we can remove it.

For your second question, it frees the memory when the cache is cleared, which right now is when the application exits. We will fix the allocation size issue and it will only allocate as much as cutensornet needs.
