### ISSUE TITLE
fft broken for non-owning types [BUG] 

### ISSUE THREAD

**Issue by luitjens** [NVIDIA/MatX#244]
the function GetFFTInputView will not compile for non-owning types.

https://github.com/NVIDIA/MatX/blob/main/include/matx_fft.h#L706-L738

The issue is that owning/non-owning is part of the type.  The output of this function will return the same owning status as the input source unless the fft_length > input length.  In this case it will allocate a new tensor and return that.  The size check is necessarily a runtime check.   This means the function tries to return different types from different non-constexpr branches which will not compile.

**Comment by luitjens** [comment]
one fix would be to make owning/non-owning a runtime property and not a compile time property.

**Comment by cliffburdick** [comment]
Is this fixed with your latest change?

**Comment by luitjens** [comment]
fixed in 7397f0103af66d72e521a0aa547d056aa120419c
