### ISSUE TITLE
ML specific operators most needed

### ISSUE THREAD

**Issue by drnikolaev** [NVIDIA/MatX#25]
**Is your feature request related to a problem? Please describe.**
Widely used by ML software, `ArgMax` and `ArgMin`(coordinate of the maximum/minimum value a.k.a. `ISAMAX/IDAMAX/ISAMIN/IDAMIN` in `BLAS` world) are surprisingly rare in tensor libraries these days. Same problem is for partial sorting (a.k.a. TopK operator). And the third thing is concatenation which would be a good addition to currently implemented slicing.

**Describe the solution you'd like**
This would be terrific to have all these facilities in MatX.

**Comment by cliffburdick** [comment]
@drnikolaev can you please describe how you use argmin/argmax in real code? One of the challenges of these functions is we supported batched reductions across an arbitrary number of dimensions, and the indices returned from argmin/argmax must also return the appropriate number of batched indices. For example, if you reduce a 4D tensor to 3D using max, besides the values stored in a 3D tensor, we would need to output another 3D tensor containing 4D coordinates (or 3D compressed/relative offsets). You can see where this would be problematic for these large tensors. Alternatively, we could enable this feature only for smaller reductions, (for example, anything going to 0D would be easy).
