### ISSUE TITLE
[FEA] Add assignment support to all operators that could use it

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/MatX#307]
LHS assignment works right now for some operators, but it's still missing on many. For example, it would be useful to do something like: 
```
(diag(A) = 1).run();
```
and the operator could assign 1 to all elements on the diagonal.

**Comment by luitjens** [comment]
Have you reviewed the code to identify which operators are missing it?  It is pretty easy to add once we know which are missing this support.

**Comment by cliffburdick** [comment]
This was completed as part of the lvalue op issue
