### ISSUE TITLE
Update eye api [FEA] 

### ISSUE THREAD

**Issue by luitjens** [NVIDIA/MatX#374]
eye api is pretty unflexible.  To use it with batching a matrix we have to create an eye of size 2 then clone across batch dims.

I propose a better API:

auto eye<RANK>();  

This is shapeless.   The logic is for the last RANK dims it would return 1 if indices are equal otherwise 0.  indices >=RANK are ignored

Example:

auto I = eye<2>();   // Identity matrix

I(0,0) -> 1
I(1,0) -> 0
I(0,1,1) -> 1

etc.

**Comment by luitjens** [comment]
one concern here that we need to consider is that shapeless operations won't have shape_type defined.  I'm not sure we really need a shape type defined though.  @cliffburdick can we depreciate shape_type?  it's currently incomplete in our implementations and afaik no one is really using it.  providing your own shape type is certainly untested.

**Comment by cliffburdick** [comment]
I think shape_type is only for tensors and isn't propagated into operators. tensorShape_t was already deprecated and dropped
