### ISSUE TITLE
update Print to print tensor matlab compatible [FEA] 

### ISSUE THREAD

**Issue by luitjens** [NVIDIA/MatX#376]
our current print format is not compatible with Matlab.  We should print like this:

A=[-9.2466e-01+9.9114e-01j -4.2534e-01+1.0676e+00j -2.6438e+00-6.2723e-01j 1.4518e-01+3.2016e-01j;
  -1.2087e-01-3.1101e-01j -5.7973e-01-3.4408e-01j -6.2285e-01-1.1709e+00j -3.2839e-01-5.3706e-01j;
 -1.0745e+00+1.3390e+00j -3.6314e-01-2.4011e-01j -1.6711e+00+1.2149e+00j 2.2655e+00-2.0518e-01j;
 3.1168e-01+1.2999e+00j -1.8419e-01+2.1812e-01j 1.2866e+00-1.2135e+00j 1.1820e+00-1.3723e+00j ]

This would allow us to directly copy that output into matlab for debugging.

**Comment by tmartin-gh** [comment]
Feature request implemented by https://github.com/NVIDIA/MatX/pull/593.  Closing.

**Comment by tmartin-gh** [comment]
Feature request implemented by https://github.com/NVIDIA/MatX/pull/593.  Closing.
