### ISSUE TITLE
implement is close operator [FEA] 

### ISSUE THREAD

**Issue by luitjens** [NVIDIA/MatX#379]
we should implement the isclose operator for comparing tensors.

https://www.w3schools.com/python/ref_math_isclose.asp

**Comment by luitjens** [comment]
I think we should have isclose(A,B) which returns a boolean tensor of the same size.  Then the reduction can be done with all().

**Comment by luitjens** [comment]
maybe we implement an isclose pointwise operator and allclose reduction?

**Comment by cliffburdick** [comment]
Yeah, maybe we need two separate versions. I'd imagine almost everyone would want to reduce it afterwards, but look at the larger matrix for statistics or to find where problems are
