### ISSUE TITLE
[BUG] INTERFACE_INCLUDE_DIRECTORIES

### ISSUE THREAD

**Issue by siegLoesch** [NVIDIA/MatX#414]
I started to get known to <MatX> via starting to follow the tutorial: 01_introduction.ipynb. For configuration an build a cmake file:
[CMakeLists.txt](https://github.com/NVIDIA/MatX/files/11440397/CMakeLists.txt).
Generating the project yields to an error saying that target <matx::matx> has an INTERFACE_INCLUDE_DIRECTORy which is not present. Namely: "include/kernels".
This is added to the installationvia the copy command top CMakeLists.txt file at line 226 [install(DIRECTORY include/ DESTINATION include)] and implemented as part of the INTERFACE_INCLUDE_DIRECTORIES via the comman <target_include_directories> at lines 91 and 92 [target_include_directories(matx INTERFACE "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/kernels>" "$<INSTALL_INTERFACE:include/kernels>")].
Inside the source tree of Matx the kernels are inside "include/**matx**/kernels" and NOT at "include/kernels". To workaround for now I modiefied the command "target_include_directories(..." as follows:
_target_include_directories(matx
	INTERFACE
		"$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/**matx**/kernels>"
		"$<INSTALL_INTERFACE:include/**matx**/kernels>"
)_                                        

I am using (should be irrelevant here):
cmake version 3.26.3
Debian bookworm
NVIDIA GeForce RTX 2060

Please counter check my findings and let me know if am wrong.

Best regards
Siegfried

**Comment by cliffburdick** [comment]
Hi @siegLoesch, this should be fixed in #416 . Can you see if it addresses your concerns?

**Comment by siegLoesch** [comment]
Hi Cliff,
It does perfectly fine. I applied your patch to unmodified sources without error:
_Applying patch file: $HOME/installOpt/gpu/MatXPatches/416.patch
patching file CMakeLists.txt
patching file bench/CMakeLists.txt
patching file docs_input/notebooks/exercises/compile_and_run.sh
patching file examples/CMakeLists.txt
patching file test/CMakeLists.txt_
The configure and build was done without error. The check of _matx-targets.conf_ showed correct _INTERFACE_INCLUDE_DIRECTORIES_ and a simple example (_matx::permute_) using _cmake_ as build system with _find_package(matx CONFIG REQUIRED)_ succeded to configure and build. The executable yields expected results.

Thanks a lot and best regards
Siegfried
