### ISSUE TITLE
[FEA] Add `outer()` for outer product

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/MatX#509]
Use cuBLAS *ger functions

**Comment by luitjens** [comment]
If we have something like outer_impl(A, X, Y) where A is batch_dims x N x M and X is batch_dims x N and y is batch_dims x M then we should be able to do this pretty easily by having outer internally clone X to X is batch_dims x N x 1 and clone Y to batch_dims x 1 x M then call matmul_impl.  

Note we should probably also support the axis parameter to match matmul/matvec.

**Comment by luitjens** [comment]
@cliffburdick fixed?
