### ISSUE TITLE
[BUG] `cmake_sample_project` cannot build when setting `MATX_EN_CUTLASS=ON`

### ISSUE THREAD

**Issue by lucifer1004** [NVIDIA/MatX#590]
**Describe the Bug**
See the title.

**To Reproduce**
Build `cmake_sample_project` with `MATX_EN_CUTLASS=ON`:

```sh
cmake -S examples/cmake_sample_project -B build -DMATX_EN_CUTLASS=ON
cmake --build build
```

The compiler would complain about missing `cutlass` headers:

```
  38 | #include "cutlass/gemm/device/gemm.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/sample_matx.dir/build.make:77: CMakeFiles/sample_matx.dir/src/single.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:696: CMakeFiles/sample_matx.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

There seems to be some issue with MatX's `CMakeLists.txt`, which does not handle the inclusion of `cutlass` headers correctly.

**Expected Behavior**
Build should work.

**Comment by cliffburdick** [comment]
Hi @lucifer1004, CUTLASS hasn't been tested since 3.x was released due to the long compile times. Is there a reason you're trying to use CUTLASS? Currently we use cuBLASLt as the GEMM backend.

**Comment by lucifer1004** [comment]
Thank you for the quick reply. I am just trying this project and testing each compile option. I do not necessarily need to use CUTLASS.

**Comment by cliffburdick** [comment]
Thanks. We will remove it as an option since it's not used currently. If you see any functionality missing please let us know. Also let me know if it's okay to close this

**Comment by lucifer1004** [comment]
I just found it was the same case with `MATX_EN_PYBIND11=ON`.

Error message:

```
build/_deps/pybind11-src/include/pybind11/cast.h(446): error: pointer to incomplete class type "_frame" is not allowed
                  "  " + handle(frame->f_code->co_filename).cast<std::string>() +
```

**Comment by cliffburdick** [comment]
This appears to be a different issue. What compiler are you using?

**Comment by lucifer1004** [comment]
OK, then I'll close this issue and open a new one for that.
