### ISSUE TITLE
[FEA] cuTENSOR 2.0 support

### ISSUE THREAD

**Issue by lucifer1004** [NVIDIA/MatX#595]
Now that cuTENSOR 2.0 has been released for some time, I think it is natural for MatX to follow this update and enjoy the performance gains brought about by this new version.

**Comment by lucifer1004** [comment]
I just realized that since `cuTensorNet` is used in `MatX`, this update is blocked by when `cuTensorNet` would adopt `cuTensor 2.0`.

**Comment by leofang** [comment]
cuQuantum 24.03 will move to use cuTENSOR 2.

**Comment by lucifer1004** [comment]
> cuQuantum 24.03 will move to use cuTENSOR 2.

Thanks for the information.

**Comment by cliffburdick** [comment]
@lucifer1004 you just have read my mind because we were just talking about this. I'll try to get to it next week. Do you use einsum right now?

**Comment by lucifer1004** [comment]
I need to use einsum. See #597.

**Comment by cliffburdick** [comment]
@lucifer1004 we will wait until the new cuquantum is released so that it's compatible with cutensor 2.x.

**Comment by cliffburdick** [comment]
@lucifer1004 the existing (older) cutensor + einsum is useable now and we will integrate the new cutensornet once ready

**Comment by leofang** [comment]
FYI cuQuantum 24.03 is out.

**Comment by cliffburdick** [comment]
Updated to cuQuantum 24.03 and verified fix.
