### ISSUE TITLE
[QST] How to get the underlying array of a tensor?

### ISSUE THREAD

**Issue by HugoPhibbs** [NVIDIA/MatX#672]
Hi, I'm a bit new to MatX, so pls bear with me.

How would I go about getting a pointer to the underlying array of a tensor? Similar to how it is done in Arrayfire with something like:

```
af::array A = ...;
int *A_d = A.device<int>();
```

I wish to do this because I want to use MatX in an application originally built with ArrayFire - the idea being to use MatX for reductions only - something that Arrayfire is quite slow at.

**Comment by cliffburdick** [comment]
> Hi, I'm a bit new to MatX, so pls bear with me.
> 
> How would I go about getting a pointer to the underlying array of a tensor? Similar to how it is done in Arrayfire with something like:
> 
> ```
> af::array A = ...;
> int *A_d = A.device<int>();
> ```
> 
> I wish to do this because I want to use MatX in an application originally built with ArrayFire - the idea being to use MatX for reductions only - something that Arrayfire is quite slow at.

If you have an existing tensor `t` it would be `t.Data()`.
