### ISSUE TITLE
[QST] Somewhat cryptic error message when finding tensor norm.

### ISSUE THREAD

**Issue by HugoPhibbs** [NVIDIA/MatX#677]
I'm attempting to find the norm along the 2nd dimension of a 3D tensor, and I'm getting a somewhat cryptic error message. Basically my code looks like this:

```
// YBatch is an ArrayFire array

auto distancesBatch_t = matx::make_tensor<float>({5, 6});
auto YBatch_t = matx::make_tensor<float>(YBatch.device<float>(), {5, 6, 3}); // Strides (18, 3, 1)

auto afCudaStream = getAfCudaStream();

(distancesBatch_t = matx::matrix_norm(YBatch_t, {2}, matx::NormOrder::FROB)).run(afCudaStream);  // Exception thrown on this line
```

I get this error:

```
unknown file: Failure
C++ exception with description "matxException (matxInvalidSize: size == 0 || size == Size(i): incompatible op sizes:T2_f32" thrown in the test body.
```

If it's helpful `matx::print(YBatch_t)` look roughly like:

```
iciTensor{float} Rank: 3, Sizes:[5, 6, 3], Strides:[18,3,1]
[000000,:,:]
000000:  1.0000e+00  2.0000e+00 -2.0000e+00 
000001: -2.0000e+00  3.0000e+00  1.0000e+00 
000002:  0.0000e+00 -2.0000e+00  0.0000e+00 
000003:  0.0000e+00  2.0000e+00  0.0000e+00 
000004:  0.0000e+00 -1.0000e+00  1.0000e+00 
000005:  0.0000e+00  1.0000e+00 -2.0000e+00 

... More rows
```

Just from looking at this, the matrix sizes look ok - so I'm not totally sure what the error messages are about. Would anybody be able to help me out with this? Thx

**Comment by cliffburdick** [comment]
Hi @HugoPhibbs , the first thing I see is it's a matrix norm, but you're trying to do it across a single axis (vector). Does it work if you leave out the axis?

I agree the error can be better

**Comment by HugoPhibbs** [comment]
My bad, I think it was because I was using `matrix norm` and not `vector_norm` - I wasn't aware of a big difference between the two.

**Comment by cliffburdick** [comment]
I will add a check for that. For reference, the reason we gave them different names compared to numpy is we allow arbitrary matching, and numpy doesn't. So any rank tensor 2 or higher it's not clear without a different function which you're trying to do.
