### ISSUE TITLE
[QST] Subtracting one tensor from another with different shape

### ISSUE THREAD

**Issue by HugoPhibbs** [NVIDIA/MatX#680]
Hi. I wish to subtract one tensor `b` off another tensor `a`, except these two tensors don't have the same shape - albeit they should be compatible.

Basically my code looks like:

```cpp
// Creation of a and b above.

print(a); //shape [5, 6, 3]
print(b); //shape [5, 1, 3]

print(a - b); // Fails here. A similar computation on NumPy would be fine. Expect a shape of (5, 6, 3)
```

I get an exception on the final line that looks like:

```
unknown file: Failure
C++ exception with description "matxException (matxInvalidSize: size == 0 || size == Size(i): incompatible op sizes:" thrown in the test body.
```

thx

**Comment by cliffburdick** [comment]
Hi @HugoPhibbs , those tensors are not compatible with our current compatibility rules. Python does allow this it looks like, so we can look at allowing it. It would not allow it if the inner dim was anything but 1. If you need a workaround I think you can do this with `repmat`.

**Comment by cliffburdick** [comment]
I *think* this should work, but I have not tried it:

```
print(a - repmat(b, {1, 6, 1}));
```

**Comment by HugoPhibbs** [comment]
@cliffburdick, thx for reply.

`repmat` allocates new memory though right? - just checking the documentation it seems to return a new operator? In practice, my `b` tensor can get very large, in these cases `repmat` may not be all that appropriate.

**Comment by cliffburdick** [comment]
No, repmat, much like almost all operators in matx are lazy and do not allocate anything. They simply access the same inner element repeatedly when it goes to higher indices.

You may want to read this concepts section: https://nvidia.github.io/MatX/basics/concepts.html

The key point is that almost everything in this library is an operator. An operator is just an interface that an object has to adhere to. A tensor is an operator as well. The return type of repmat is an operator, but you can use it as input into any other operator. This allows you to write complex expressions that don't allocate any extra memory and use deferred evaluation.

**Comment by cliffburdick** [comment]
@HugoPhibbs it looks like the sizes you gave in the example above do in fact work in MatX. I tried this: 
```
    auto t = make_tensor<float>({5,6,3});
    auto t2 = make_tensor<float>({5,1,3});
    (t = t2).run();
    (t - t2).run();
    print(t - t2);
```

Both of these work correctly.

**Comment by HugoPhibbs** [comment]
@cliffburdick ok thx. Must've been an error further up the operator stack surfacing when doing run.
