### ISSUE TITLE
[FEA] Better error messages with incompatible matrix sizes

### ISSUE THREAD

**Issue by HugoPhibbs** [NVIDIA/MatX#681]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying sometimes to get error messages such as:
```
unknown file: Failure
C++ exception with description "matxException (matxInvalidSize: size == 0 || size == Size(i): incompatible op sizes:" thrown in the test body.
```
I've found that these can be raised for multiple reasons - e.g. trying to allocate a tensor into a space that is too big/small for it, or trying to do an operation on two tensors that have incompatible sizes. E.g. the above error is raised for the below code:

```cpp
auto a = matx::ones({4, 3, 6});
auto b = matx::zeros({4, 3, 9});
matx::print(a-b);
```

**Describe the solution you'd like**
I would like a more helpful error message, for example when doing an operation with two tensors of incompatible operation sizes, this should be explicitly mentioned. For example, in NumPy, I get a helpful behaviour that looks like the below:

```python
a = np.ones((4, 3, 6));
b = np.ones((4, 3, 9));
a-b
```

```
a-b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (4,3,6) (4,3,9) 
```

**Describe alternatives you've considered**
Yes you could debug manually and figure out what the problem, but a more helpful error message could point you in the right direction right off the bat.

**Comment by cliffburdick** [comment]
Thanks @HugoPhibbs , we will see if we can add this soon. I agree it's not too easy to tell right now.
