### ISSUE TITLE
[BUG] Unit Test Failure

### ISSUE THREAD

**Issue by seanajohnston** [NVIDIA/MatX#97]
Most of the unit tests pass. I think this one may be towards the end of the list. One test fails on an assertion, and a subsequent test throws an exception.

After pulling updates from the main branch, 
built and run using:
```
cmake -DBUILD_TESTS=ON ..
make -j
cd test
./matx_test
```

Output of failures:
```
Comparison failed at /path/to/MatX/test/00_transform/MatMul.cu:136:0/64: val=0.438721+13.132812j file=8.766909+-0.536683j (c)
/path/to/MatX/test/00_transform/MatMul.cu:136: Failure
Failed
[  FAILED  ] MatMulTestFloatTypes/6.MediumRect, where TypeParam = matx::matxHalfComplex<matx::matxHalf<__half> > (255 ms)
[----------] 3 tests from MatMulTestFloatTypes/6 (262 ms total)

[----------] 3 tests from MatMulTestFloatTypes/7, where TypeParam = matx::matxHalfComplex<matx::matxHalf<__nv_bfloat16> >
[ RUN      ] MatMulTestFloatTypes/7.SmallRect
matxException (matxMatMulError: ret == CUBLAS_STATUS_SUCCESS) - /path/to/MatX/include/matx_matmul.h:505

Stack Trace:
 ./matx_test() [0x4cd619]
 ./matx_test() [0xd58d45]
 ./matx_test() [0xd4ed50]
 ./matx_test() [0xd40f9a]
 ./matx_test() [0xd3873b]
 ./matx_test : void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x65
 ./matx_test : void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x4b
 ./matx_test : testing::Test::Run()+0xea
 ./matx_test : testing::TestInfo::Run()+0x122
 ./matx_test : testing::TestSuite::Run()+0x133
 ./matx_test : testing::internal::UnitTestImpl::RunAllTests()+0x3c1
 ./matx_test : bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x65
 ./matx_test : bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x4b
 ./matx_test : testing::UnitTest::Run()+0xaa
 ./matx_test() [0x4a3c99]
 ./matx_test() [0x4a27d6]
 /lib64/libc.so.6 : __libc_start_main()+0xf5
 ./matx_test() [0x4a266e]
```

**System details:**
 - GPU: Quadro RTX 5000
 - OS: CentOS 7
 - CUDA version: 11.5
 - gcc/g++ version: 9.3.1 20200408 (Red Hat 9.3.1-2)
 - cmake version: 3.22.1

**Comment by cliffburdick** [comment]
Hi @seanajohnston , this is due to that card not supporting bfloat16, and we need to selectively disable that test based on the compute capability. Thanks for reporting it.

**Comment by seanajohnston** [comment]
Ok sir. @cliffburdick Thanks for you reply and good to know.

**Comment by cliffburdick** [comment]
Reopening just as a reminder to fix.

**Comment by cliffburdick** [comment]
hi @seanajohnston , this is fixed, and you should see the tests be skipped if your hardware doesn't support the operation.

**Comment by syoyo** [comment]
@cliffburdick 

FYI `half float` test  fail on my P100 configuration.

OS: Ubuntu 20.04
Driver: 510.47.03 (CUDA 11.6)
CUDA_ARCHITECTRURE: 60
GPU: Tesla P100
MatX revision: 5eef2dcd79ab704b9825e09008750871af33077c

P100 is said to support fp16, so the test should pass :thinking: 

```
[----------] 4 tests from MatMulTestFloatTypes/6, where TypeParam = matx::matxHalfComplex<matx::matxHalf<__half> >
[ RUN      ] MatMulTestFloatTypes/6.SmallRect
matxException (matxMatMulError: ret == CUBLAS_STATUS_SUCCESS) - /home/syoyo/work/MatX/include/matx_matmul.h:539

Stack Trace:
 ./test/matx_test : ()+0x10f45d
 ./test/matx_test : ()+0xb8a992
 ./test/matx_test : ()+0xb7549e
 ./test/matx_test : ()+0xb5e1b3
 ./test/matx_test : ()+0xb5646b
 ./test/matx_test : void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::)(), char const)+0x69
 ./test/matx_test : void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::)(), char const)+0x5e
 ./test/matx_test : testing::Test::Run()+0xf2
 ./test/matx_test : testing::TestInfo::Run()+0x140
 ./test/matx_test : testing::TestSuite::Run()+0x149
 ./test/matx_test : testing::internal::UnitTestImpl::RunAllTests()+0x41f
 ./test/matx_test : bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::)(), char const)+0x69
 ./test/matx_test : bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::)(), char const)+0x5e
 ./test/matx_test : testing::UnitTest::Run()+0xc4
 ./test/matx_test : ()+0x1015f2
 ./test/matx_test : ()+0x10071a
 /lib/x86_64-linux-gnu/libc.so.6 : _libcstart_main()+0xf3
 ./test/matx_test : _start()+0x2e
```

**Comment by cliffburdick** [comment]
> @cliffburdick
> 
> FYI `half float` test fail on my P100 configuration.
> 
> OS: Ubuntu 20.04 Driver: 510.47.03 (CUDA 11.6) CUDA_ARCHITECTRURE: 60 GPU: Tesla P100 MatX revision: [5eef2dc](https://github.com/NVIDIA/MatX/commit/5eef2dcd79ab704b9825e09008750871af33077c)
> 
> P100 is said to support fp16, so the test should pass 🤔
> 
> ```
> [----------] 4 tests from MatMulTestFloatTypes/6, where TypeParam = matx::matxHalfComplex<matx::matxHalf<__half> >
> [ RUN      ] MatMulTestFloatTypes/6.SmallRect
> matxException (matxMatMulError: ret == CUBLAS_STATUS_SUCCESS) - /home/syoyo/work/MatX/include/matx_matmul.h:539
> 
> Stack Trace:
>  ./test/matx_test : ()+0x10f45d
>  ./test/matx_test : ()+0xb8a992
>  ./test/matx_test : ()+0xb7549e
>  ./test/matx_test : ()+0xb5e1b3
>  ./test/matx_test : ()+0xb5646b
>  ./test/matx_test : void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::)(), char const)+0x69
>  ./test/matx_test : void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::)(), char const)+0x5e
>  ./test/matx_test : testing::Test::Run()+0xf2
>  ./test/matx_test : testing::TestInfo::Run()+0x140
>  ./test/matx_test : testing::TestSuite::Run()+0x149
>  ./test/matx_test : testing::internal::UnitTestImpl::RunAllTests()+0x41f
>  ./test/matx_test : bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::)(), char const)+0x69
>  ./test/matx_test : bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::)(), char const)+0x5e
>  ./test/matx_test : testing::UnitTest::Run()+0xc4
>  ./test/matx_test : ()+0x1015f2
>  ./test/matx_test : ()+0x10071a
>  /lib/x86_64-linux-gnu/libc.so.6 : _libcstart_main()+0xf3
>  ./test/matx_test : _start()+0x2e
> ```

thanks @syoyo , I'll reopen and take a look.

**Comment by cliffburdick** [comment]
Hi @syoyo , this should be fixed. The problem wasn't that P100 supports fp16, but it does not support tensor core fp16, which currently our matrix multiply library uses. If you would find it useful to have the P100 support non-TC matrix multiplies can you open up an issue requesting the feature? Thanks for finding it.

**Comment by syoyo** [comment]
@cliffburdick Thanks! For me, at the moment non-TC fp16 matmul is not so important when using MatX on P100.
